name: Build and Release Combine Go Program

on:
  push:
    tags:
      - 'v*'  # Trigger only for version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, darwin-arm64]  # Added darwin-arm64
        go-version: [1.18, 1.19, 1.20]  # Specify the Go versions to test (optional)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the program for ${{ matrix.os }}
        run: |
          # Set the correct OS and architecture for each platform
          if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "windows-latest" ]]; then
            GOOS=${{ matrix.os }} GOARCH=amd64 go build -o combine-${{ matrix.os }}-${{ matrix.go-version }} ./combine.go
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            GOOS=darwin GOARCH=amd64 go build -o combine-darwin-amd64-${{ matrix.go-version }} ./combine.go
          elif [[ "${{ matrix.os }}" == "darwin-arm64" ]]; then
            GOOS=darwin GOARCH=arm64 go build -o combine-darwin-arm64-${{ matrix.go-version }} ./combine.go
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: combine-${{ matrix.os }}
          path: |
            combine-${{ matrix.os }}-${{ matrix.go-version }}
            combine-darwin-arm64-${{ matrix.go-version }}  # Upload darwin-arm64 artifact if built

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            combine-ubuntu-latest-*.tar.gz
            combine-macos-latest-*.tar.gz
            combine-windows-latest-*.tar.gz
            combine-darwin-arm64-*.tar.gz  # Include darwin-arm64 release file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
